server:
   port: 8890

logging:
    path: logs
    file: userManager.log


spring:
   application:
          name: report
   datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://10.10.221.173:3306/course
       username: root
       password: 123456

mybatis:
    type-aliases-package: com.course.model
    mapper-locations:
       - mapper/*
